### ISSUE TITLE
Cannot buy booster packs

### ISSUE THREAD

**Issue by gra2ie** [sarhatabaot/TradingCards#121]
### Description

No matter what I do, I cannot buy a booster pack. I can give them to myself, but they cannot be purchased. I have given myself the permissions to buy the packs, given myself OP, made sure all the vault stuff is enabled and still will not work. Used to work fine on the original Xen's release, but since updating to this I cannot figure it out for the life of me. All values are default, and my server account has over $2000 in it, and none of the packs work.

### Steps to reproduce

Install the .jar, give yourself all the permissions you need, and attempt to buy a booster pack.

### Expected Behaviour

I expected to be able to purchase a booster pack.

### Server Software

Spigot, 1.18.2

### Minecraft Version

1.18.x

**Comment by sarhatabaot** [comment]
Re-opened since issue is not resolved for a user.
