### ISSUE TITLE
Error while enabling TradingCards

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/TradingCards#153]
### Description

Error on server load.

### Steps to reproduce

1. Run server

### Expected Behaviour

Server should start with no errors.

### Server Log

https://bin.bloom.host/viwacayuco.apache

### Server Software

Purpur git-Purpur-1579 

### TradingCards version

5.7.0-SNAPSHOT-20220705-1958

### Minecraft Version

1.18.x

**Comment by isaaclepes** [comment]
Came here for the same error.  Compiling the latest source solved the issue.

**Comment by sarhatabaot** [comment]
Do notice you can get latest builds from https://ci.codemc.io/job/sarhatabaot/job/TradingCards/ .
