### ISSUE TITLE
Every command excluding reload doesnt work

### ISSUE THREAD

**Issue by TheHalfBunny** [sarhatabaot/TradingCards#270]
### Description

Every command doesnt work when ran, except reloading the configs

### Steps to reproduce

1. literally just run any command

### Expected Behaviour

i expected it to create a card but shows "Unknown command"

### Screenshots

https://github.com/sarhatabaot/TradingCards/assets/84818665/a96a1474-a4fe-4f21-929a-d9eab59eb5d9

### Server Software

Paper 1.19.3

### TradingCards version

TradingCards-5.7.17

### Minecraft Version

1.19.x

**Comment by sarhatabaot** [comment]
Looking into this. Do you have the correct permissions?

**Comment by sarhatabaot** [comment]
Keep in mind that with `/cards create` you must also specify a rarity and a series. If you don't you will get a command unknown.

**Comment by TheHalfBunny** [comment]
> Keep in mind that with `/cards create` you must also specify a rarity and a series. If you don't you will get a command unknown.

literally every command i get unknown

**Comment by sarhatabaot** [comment]
> > Keep in mind that with `/cards create` you must also specify a rarity and a series. If you don't you will get a command unknown.
> 
> literally every command i get unknown

Please send me your startup log, either here or in a dm on discord: sarhatabaot

**Comment by TheHalfBunny** [comment]
> > > Keep in mind that with `/cards create` you must also specify a rarity and a series. If you don't you will get a command unknown.
> > 
> > 
> > literally every command i get unknown
> 
> Please send me your startup log, either here or in a dm on discord: sarhatabaot
> 
> Also, update your trading cards to the latest version.

now it started working, somehow
