### ISSUE TITLE
Once a shiny card drops, all succeeding cards have the enchantment on it

### ISSUE THREAD

**Issue by ketelsb** [sarhatabaot/TradingCards#39]
**Describe the bug**
Once a shiny card drops, all succeeding cards have the enchantment on it

**To Reproduce**
Wait until you have an enchanted card. The next one will be enchanted even if it is not shiny

**Expected behavior**
A shiny card does not have an enchantment on it

**Comment by sarhatabaot** [comment]
Fixed in #40
