### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by isaaclepes** [sarhatabaot/TradingCards#56]
I have been updating DarnComputer's Xen's Trading Cards Resource Pack to keep it compatible with newer versions of OptiFine as well as adding new card backs for each year. I used to keep this under a fork of Xen'sTC, but I decided to make it a standalone repository.

https://github.com/isaaclepes/TradingCardsResource

I thought you may wish to add this to your wiki under add-ons.

**Comment by sarhatabaot** [comment]
Added under the addon page!
