### ISSUE TITLE
Card Series Year

### ISSUE THREAD

**Issue by isaaclepes** [sarhatabaot/TradingCards#58]
**Describe the solution you'd like**
With the original XTC plugin, changing the series of a card only updates all future cards.  Currently existing cards retain their prior series (unless added to a deck) and can still be used to complete the sets they are for.  Aside from ensuring a similar functionality in your fork, I would also like to suggest a separate NBT value for the card's year.

The resource pack I am developing for the plugin just changes the card's back texture each year.  I also am planning on making holiday series cards, but the normal schedule function you added should work nicely for that.  With the holiday series, the front textures will be different from normal but the back I would like to have the year's card back.  The reasoning is that some players collect the cards and seem to enjoy trying to complete all sets each year, not just turn them in for the reward.

So a card might have:

isYearly=true
which sets an NBT value of year=current.year
Then card can be a part of the default, Halloween, etc. series and still get the year's back texture.

**Describe alternatives you've considered**
Currently, this requires a global search and replace for the year in the config at the turn of each new year.

**Additional context**

Not important to the discussion, but here is a prototype I made for a Valentine's Day series card
![image](https://user-images.githubusercontent.com/54421422/148571356-e07cdfa3-356d-4d5e-a70e-3da478a86a69.png)

**Comment by sarhatabaot** [comment]
I'm not really sure about this one. 
We could just create a different series for every year. i.e. halloween2022, chrimstas2022 etc.
Perhaps we could add an "additional nbt" feature that allows you to add whatever nbt key values you want.

**Comment by isaaclepes** [comment]
Apologies for the delayed reply, life happened.

Changing series each year was the manual option I mentioned above, which is what server admins currently need to do to see the new card backs.

I was hoping for an auto-incrementing year, either in Lore or as a hidden NBT tag. I suppose I could work out a BASH script to run as a cronjob parse the config and change the year using sed, but this might be a bit difficult for other server admins to implement. The only issue then would be ensuring that the Deck database tracks the original series data and doesn't update old cards to the new series designated in the config.

**Comment by sarhatabaot** [comment]
Closing the issue for now, if I decide to implement this I will re-open this issue.
