### ISSUE TITLE
Trading cards for packs (in shops)

### ISSUE THREAD

**Issue by grimer30** [sarhatabaot/TradingCards#61]
Hi, this is more of a question than a feature request, sorry! Great plugin by the way!

I see that rewards for collecting full sets of rarities aren't in yet, but that's not quite what I want anyway! Is there a way of doing this:
-Players can only get cards by buying booster packs which contain (for example) 3 common cards.
-Player can trade in any 3 different cards for 1 card of the next rarity up; e.g. 3 common for 1 uncommon.
-Ideally, being able to trade a number of cards for a booster pack; maybe 9 common cards for a pack of 3 uncommons, or a number of common cards to get a pack of random other cards of the same rarity (if they don't like the ones they have?)

Perhaps I could use a different simple shop plugin that can take in and give out items and take 3 common_card (is there an id for shops like that?) for 1 uncommon_card and make a shop for each rarity? (This would require players to go to a specific place on the server to trade them in, rather than type /card upgrade or whatever the command would be)

Seems to me that asking players to complete a full set of rarities to get a reward might be kind of difficult if I've added a few dozen more cards to the server, haha! A way of trading in just a few of them would be much more helpful, if there's some way I could add that to my server :)

**Comment by isaaclepes** [comment]
For disabling drops, see https://github.com/sarhatabaot/TradingCards/blob/master/tradingcards-plugin/src/main/resources/settings/chances.yml
# enter the chances for various rarities below, out of 100,000. 1 = 1 in 100,000 or 0.001%
# 10,000 = 10% chance, 1000 = 1% chance, 100 = 0.1% chance, 10 = 0.01% chance, 1 = 0.001% chance
# chances are in descending order - make sure the chances for common are higher than uncommon etc.
# **if a type is omitted from this section, the rarity won't drop at all from that type.**

and for the rewards, see https://github.com/sarhatabaot/TradingCards/blob/master/tradingcards-plugin/src/main/resources/settings/rarities.yml

replace "eco give %player% 100" with "cards give pack %player% name-of-pack"

**Comment by grimer30** [comment]
Hi, thanks very much! This would be really helpful and exactly what I was searching for, but what threw me off when I searched previously was at the top of your second link: "rewards: [...] not implemented yet"?
Is this comment just a left-over, and rewards are implemented? :)

**Comment by isaaclepes** [comment]
To be honest, I hadn't noticed that. I would have to defer to @sarhatabaot for that one.

**Comment by grimer30** [comment]
Thanks very much! TCRecipes would be perfectly and exactly what I want, if only the parameters could be "general" (as you just said!):

From:
  result: "uncommon,blaze,1,false"
  recipe:
    - "common,zombie,4,false"
To:
  result: "uncommon,,1,false"
  recipe:
    - "common,,4,false"

Would be great 😄

**Comment by sarhatabaot** [comment]
Hi, bit of an update for this. I'm splitting this feature request into 2, I will reference them using other issues below.

- The cards upgrade feature.
- Trade cards for booster packs.

**Comment by sarhatabaot** [comment]
Implemented in #186 & #184 !
