### ISSUE TITLE
Method to upgrade existing cards

### ISSUE THREAD

**Issue by isaaclepes** [sarhatabaot/TradingCards#62]
**Is your feature request related to a problem? Please describe.**
Related to this suggestion for the Trading Cards Resource Pack: https://github.com/isaaclepes/TradingCardsResource/issues/3
If the matching is updated to the model ID format, the resource pack will cease to work with existing cards.

**Describe the solution you'd like**
Some method for the plugin to recognize cards using the old format and modify/replace them to add NBT data for model data.

**Describe alternatives you've considered**
Creating 2 separate resource packs, one for users of XTC and one for users of TC 5.5.x+.  Not ideal and could create a barrier to upgrade for current XTC users considering TC.

A special data pack that detects item entities that match for cards and inserts the correct model ID based on their titles.  This would be quite difficult to implement and could cause server performance impacts as it must check @e entities for the correct ones.

**Additional context**

**Comment by sarhatabaot** [comment]
I probably won't implement this. 
It's pretty complex and resource intensive. In a small scale it's probably fine, but if you have more than 10 players collecting cards it's too much.
I didn't mention it in https://github.com/isaaclepes/TradingCardsResource/issues/3, but users of the original plugin probably modified their card display name anyways. Restricting the use of the original resource pack to just the format in  https://github.com/isaaclepes/TradingCardsResource.

Server owners "upgrading" to TC from XTC should probably consider resetting their data and starting a new. We had a set-up where we manually went through and replaced "broken" or non-nbt items, but that's something I don't really recommend doing.

**Comment by sarhatabaot** [comment]
Closing the issue for now, if I decide to implement this I will re-open this issue.
